miniblog/miniblog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name="home"),
    path('about/', views.about,name="about"),
    path('contact/', views.contact,name="contact"),
    path('dashboard/', views.dashboard,name="dashboard"),
    path('signup/', views.user_signup,name="signup"),
    path('login/', views.user_login,name="login"),
    path('logout/', views.user_logout,name="logout"),
    path('edit/<int:id>/', views.user_edit,name="edit"),
    path('delete/<int:id>/', views.user_delete,name="delete"),
    path('addpost/', views.addpost,name="addpost"),
]

miniblog/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField()
    

miniblog/blog/forms.py
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm ,UsernameField
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext ,gettext_lazy as _
from .models import Post
class SignUpForm(UserCreationForm):
    password1 =forms.CharField(label='password' , widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 =forms.CharField(label='Confirm Password (again)', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields =['username','first_name','last_name','email']
        labels={'first_name':"First Name",
        "last_name":"Last Name",
        "email":"Email"}
        widgets={'username':forms.TextInput(attrs={'class':'form-control'}),
        'first_name':forms.TextInput(attrs={'class':'form-control'}),
        'last_name':forms.TextInput(attrs={'class':'form-control'}),
        'email':forms.EmailInput(attrs={'class':'form-control'})}

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus':True ,'class':'form-control'}))
    password = forms.CharField(label=_("pasword"),strip=False,widget=forms.PasswordInput
    (attrs={'auto-complete':'current-password','class':'form-control'}))

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','desc']
        labels={'title':'Title','desc':'Description'}
        widgets={'title':forms.TextInput(attrs={'class':'form-control'}),
        'desc' : forms.Textarea(attrs={'class':'form-control'})}

miniblog/blog/views.py
from django.shortcuts import render,HttpResponseRedirect
from .forms import SignUpForm ,LoginForm ,PostForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout 
from .models import Post
from django.contrib.auth.models import Group
# Create your views here.

#Home
def home(request):
    posts=Post.objects.all()
    return render(request,'blog/home.html',{'posts':posts})

#View
def about(request):
    return render(request,'blog/about.html')

#Contact
def contact(request):
    return render(request,'blog/contact.html')

#dashboard
def dashboard(request):
    if request.user.is_authenticated:
        posts=Post.objects.all()
        user =request.user
        full_name =user.get_full_name()
        gps=user.groups.all()
        return render(request,'blog/dashboard.html',{'posts':posts,'full_name':full_name,"groups":gps})
    else :
        return HttpResponseRedirect('/login/')


#user_logout
def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect('/login/')

#signup
def user_signup(request):
    if request.method=="POST":
        form=SignUpForm(request.POST)
        if form.is_valid():
            messages.success(request,"Congratulations !! You have become an Author")
            user=form.save()
            group=Group.objects.get(name="Author")
            user.groups.add(group)
    else:
        form=SignUpForm()
    return render(request,'blog/signup.html',{'form':form})

#login
def user_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/dashboard/')
    else:
        if request.method=="POST":
            form=LoginForm(request=request,data=request.POST)
            if form.is_valid():
                uname=form.cleaned_data['username']
                upass=form.cleaned_data['password']
                user=authenticate(username=uname,password=upass)
                if user:
                    login(request,user)
                    messages.success(request,'Logged in successfully !!')
                    return HttpResponseRedirect('/dashboard/')
        form=LoginForm()
        return render(request,'blog/login.html',{'form':form})

def user_edit(request,id):
    if request.user.is_authenticated:
        if request.method=="POST":
            pi=Post.objects.get(pk=id)
            form=PostForm(request.POST,instance=pi)
            if form.is_valid():
                form.save()
                messages.success(request,'Updated post  successfully !!')
                return HttpResponseRedirect('/dashboard/')
        else:
            pi=Post.objects.get(pk=id)
            form=PostForm(instance=pi)
        return render(request,'blog/editpost.html',{'form':form})
    else:
        return HttpResponseRedirect('/login/')


def user_delete(request,id):
    if request.user.is_authenticated:
        pi=Post.objects.get(pk=id)
        pi.delete()
        messages.success(request,'Deleted post  successfully !!')
        return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')

def addpost(request):
    if request.user.is_authenticated:
        if request.method=="POST":
            form=PostForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request,'Added post  successfully !!')
                return HttpResponseRedirect('/dashboard/')
        else:
            form=PostForm()
        return render(request,'blog/addpost.html',{'form':form})
    else:
        return HttpResponseRedirect('/login/')

miniblog/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">About page</h3>
<p>
    Sidney Sheldon was a bestselling author of crime and thriller novels, in addition to writing Broadway plays and movies. He passed away in 2007, but his eighteen novels continue to find new readers every day, having sold more than 300 million copies worldwide. If you’re new to Sidney Sheldon and are wondering which book to pick up first, let Goodreads help you decide! This list ranks the top-rated Sidney Sheldon novels according to their average Goodreads user ratings.
</p>
</div>



{% endblock content %}

miniblog/blog/templates/blog/addpost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5"> Dashboard /Add Post</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add" class="btn btn-success">
        
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
    </form>

</div>
{% endblock content %}

miniblog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}" type="text/css" media="screen, projection" >
    <title></title>
  </head>
  <style>
    body{
    background-color: rgb(75,74,74);
    color : antiquewhite;
}
.jumbo-color{
  background-color: rgb(83,81,81);
}
.form-control {
  background-color:rgb(177,168,168)
}
  </style>
  <body>
    <div class="container-fluid bg-dark">

      {% include 'blog/navbar.html'%}
    </div>
  <div class="container">
    <div class="row">
      <div clas="col-sm-12">
        {% block msg %}
        {% endblock msg %}
      </div>
      <div>
    <div class="row">
      {% block side %}
      {% endblock side %}
      
      {% block content %}
      {% endblock content %}
      </div>
      </div>

<script src="{% static 'blog/js/jquery.js'%}"></script>
<script src="{% static 'blog/js/popper.js'%}"></script>
<script src="{% static 'blog/js/bootstrap.js'%}"></script>

  </body>
</html>

miniblog/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Contact page</h3>
    <form>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputEmail4">Email</label>
            <input type="email" class="form-control" id="inputEmail4">
          </div>
          <div class="form-group col-md-6">
            <label for="inputPassword4">Password</label>
            <input type="password" class="form-control" id="inputPassword4">
          </div>
        </div>
        <div class="form-group">
          <label for="inputAddress">Address</label>
          <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
        </div>
        <div class="form-group">
          <label for="inputAddress2">Address 2</label>
          <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputCity">City</label>
            <input type="text" class="form-control" id="inputCity">
          </div>
          <div class="form-group col-md-4">
            <label for="inputState">State</label>
            <select id="inputState" class="form-control">
              <option selected>Choose...</option>
              <option>...</option>
            </select>
          </div>
          <div class="form-group col-md-2">
            <label for="inputZip">Zip</label>
            <input type="text" class="form-control" id="inputZip">
          </div>
        </div>
        <div class="form-group">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="gridCheck">
            <label class="form-check-label" for="gridCheck">
              Check me out
            </label>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Sign in</button>
      </form>
</div>



{% endblock content %}

miniblog/blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% load static %}


    {% block msg %}
    
    {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}>
        <strong>{{message}}</strong>
    <button type="button" class="close" data-dismiss="alert"
aria-label="Close">
<span aria-hidden="true"> &times;</span>
</button>
</div>
    {% endfor %}
    {% endif %}

</div>

{% endblock msg %}

{% block side %}
<div class="col-sm-2 text-white my-5 text-center">
    <h4 class="my-5">Profile</h4>
    <h5>{{full_name}}</h5>
    {% for group in groups %}
    <p>{{group.name}}</p>
    {% endfor %}
</div>
{% endblock side %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Home page</h3>
    <a href="{% url 'addpost' %}" class="btn btn-success">Add post</a>
    <h4 class="text-center alert alert-info mt-3"> Show Post Information</h4>
    {% if posts %}
    <table class="table table-hover bg-white">
        <thead>
            <tr class="text-center">
                <th scope='col' style="width:2%">ID</th>
                <th scope='col' style="width:28%">Title</th>
                <th scope='col' style="width:55%">Description</th>
                <th scope='col' style="width:15%">Action</th>

            </tr>
        </thead>
      <tbody>
          {% for post in posts %}
          <tr>
              <th scopr="row">{{post.id}}</th>
              <td> {{post.title}}</td>
              <td>{{post.desc}}</td>
              <td class="text-center">
                  <a href="{% url 'edit' post.id %}" class="btn btn-warning btn-sm">Edit</a>
                 {% if perms.blog.delete_post %}
                  <form action="{% url 'delete' post.id %}" method="POST" class="d-inline">
                      {% csrf_token %}
                      <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                  </form>
                  {% endif %}
              </td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
    {% else %}
    <h4 class="text-center alert alert-warning">No Records</h4>
    {% endif %}
</div>
{% endblock content %}

miniblog/blog/templates/blog/editpost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5"> Dashboard /Update Post</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update" class="btn btn-success">
        
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
    </form>

</div>
{% endblock content %}

miniblog/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Home page</h3>
    {% for post in posts%}

    <div class="jumbotron jumbotron-fluid jumbo-color">
        <div class="container">
          <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
          <p class="lead">{{post.desc}}</p>
        
        </div>
      </div>
      <br>
      {% endfor %}
</div>



{% endblock content %}

miniblog/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Login  page</h3>
    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        <div class="form-group">
        {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>
    </div>
    
        {% endfor %}
        <br>
        <input type="submit" value="Login" class="btn btn-primary">
        {% if form.non_field_errors %}
        {% for eror in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
        {% endif %}

</div>



{% endblock content %}

miniblog/blog/templates/blog/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Mini Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}

      </ul>
    </div>
  </nav>

miniblog/blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Become an Author</h3>
    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
    {% endfor %}
    {% endif %}
    <form action="" method="POST" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        <div class="form-group">
        {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>
    </div>
    
        {% endfor %}
        <br>
        <input type="submit" value="SignUp" class="btn btn-primary">
        {% if form.non_field_errors %}
        {% for eror in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
        {% endif %}
    </form>
    

</div>



{% endblock content %}